[package]
name = "multi_key_db"
version = "0.1.0"
edition = "2018"
license = "MIT"

[dependencies]
log="0.4.14"
env_logger="0.9.0"

[dependencies.cli-table]
version = "0.4.6"
optional = true
default-features = false


[features]
default = []
cli-features = ["cli-table"]